name: isaaclab
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10.16
  - pip=25.0.1
  - numpy=1.26.4
  - matplotlib=3.10.1
  - pip:
    - gym==0.23.1
    - gymnasium==1.0.0
    - pyyaml==6.0.2
    - tensorboard==2.19.0
    - pillow==11.0.0
    - tqdm==4.67.1
    - opencv-python==4.11.0.86
    - scipy==1.15.2
    - pandas==2.2.3
    - stable-baselines3==2.5.0
    - rl-games==1.6.1
    - moviepy==1.0.3
    - tensorboardx==2.6.2.2
    - wandb==0.12.21
    - h5py==3.13.0
    - einops==0.8.1
    - rsl-rl-lib==2.2.4
    - skrl==1.4.2
    # Isaac Sim packages - these should be installed according to the IsaacLab documentation
    # pip install 'isaacsim[all,extscache]==4.5.0' --extra-index-url https://pypi.nvidia.com
    # The following packages are expected to be installed with Isaac Sim
    # and are not included in this file:
    # - isaacgym
    # - isaaclab 